version: '3.7'

services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    command: start.sh jupyter lab --NotebookApp.token=''
    ports:
      - "8888:8888"
      - "8050:8050"  # Dash port
    volumes:
      - /Users/eric/OneDrive/dev/analytics_jupyter_notebooks:/home/jovyan/work
      - /Users/eric/OneDrive/dev/analytics_demo_data:/home/jovyan/data
      - /Users/eric/OneDrive/dev:/home/jovyan/devRoot
    environment:
      - OPENAI_API_KEY
      - PEOPLE_DATA_LABS_KEY
      - CRUNCHBASE_API_KEY
      - BING_SEARCH_V7_ENDPOINT
      - BING_SEARCH_V7_SUBSCRIPTION_KEY
  