version: '3.7'

services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    command: start.sh jupyter lab --NotebookApp.token=''
    ports:
      - "8888:8888"
      - "8050:8050"  # Dash port
    volumes:
      - /Users/eric/OneDrive/dev/analytics_jupyter_notebooks:/home/jovyan/work
      - /Users/eric/OneDrive/dev/analytics_demo_data:/home/jovyan/data
      - /Users/eric/OneDrive/dev:/home/jovyan/devRoot
      - /Users/eric/OneDrive - Presidio Network Solutions/dev:/home/jovyan/presidio
    environment:
      - OPENAI_API_KEY
      - PEOPLE_DATA_LABS_KEY
      - CRUNCHBASE_API_KEY
      - BING_SEARCH_V7_ENDPOINT
      - BING_SEARCH_V7_SUBSCRIPTION_KEY
      - SOCRATE_APP_TOKEN
      - SOCRATA_APP_TOKEN_SECRET
      - SOCRATA_MYLOGIN
      - SOCRATA_MYPW
      - AZURE_OPENAI_API_KEY
      - OPENAI_API_VERSION
      - AZURE_OPENAI_ENDPOINT
       