version: '3.7'

services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    command: start.sh jupyter lab --NotebookApp.token=''
    ports:
      - "8888:8888"
      - "8050:8050"  # Dash port
    volumes:
      - C:\Users\jfaddler\OneDrive\dev\analytics_jupyter_notebooks:/home/jovyan/work
      - C:\Users\jfaddler\OneDrive\dev\analytics_demo_data:/home/jovyan/data
      - C:\Users\jfaddler\OneDrive\dev:/home/jovyan/devRoot
    environment:
      - OPENAI_API_KEY
      - PEOPLE_DATA_LABS_KEY
      - CRUNCHBASE_API_KEY
